//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour
    {
        public int IDtour { get; set; }
        public string Nombretour { get; set; }
        public string Descripciontour { get; set; }
        public Nullable<int> IDestado { get; set; }
        public Nullable<int> IDclima { get; set; }
        public Nullable<int> IDactividad { get; set; }
    
        public virtual actividad actividad { get; set; }
        public virtual clima clima { get; set; }
        public virtual lugare lugare { get; set; }
    }
}
